# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\projects\AllProjectsEver\projects\scripts\random\cbir\designs\image_editing.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class ImageEditing(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(591, 470)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(44, 62, 80);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.light_intensity_slider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.light_intensity_slider.sizePolicy().hasHeightForWidth())
        self.light_intensity_slider.setSizePolicy(sizePolicy)
        self.light_intensity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.light_intensity_slider.setObjectName(_fromUtf8("light_intensity_slider"))
        self.horizontalLayout_2.addWidget(self.light_intensity_slider)
        self.intensity_percent = QtGui.QLabel(self.centralwidget)
        self.intensity_percent.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.intensity_percent.setObjectName(_fromUtf8("intensity_percent"))
        self.horizontalLayout_2.addWidget(self.intensity_percent)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 2, 1, 1)
        self.image_frame = QtGui.QFrame(self.centralwidget)
        self.image_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.image_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.image_frame.setObjectName(_fromUtf8("image_frame"))
        self.gridLayout.addWidget(self.image_frame, 2, 0, 8, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.grayscale_slider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grayscale_slider.sizePolicy().hasHeightForWidth())
        self.grayscale_slider.setSizePolicy(sizePolicy)
        self.grayscale_slider.setOrientation(QtCore.Qt.Horizontal)
        self.grayscale_slider.setObjectName(_fromUtf8("grayscale_slider"))
        self.horizontalLayout.addWidget(self.grayscale_slider)
        self.grayscale_percent = QtGui.QLabel(self.centralwidget)
        self.grayscale_percent.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.grayscale_percent.setObjectName(_fromUtf8("grayscale_percent"))
        self.horizontalLayout.addWidget(self.grayscale_percent)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 2, 1, 1)
        self.choose_image = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.choose_image.sizePolicy().hasHeightForWidth())
        self.choose_image.setSizePolicy(sizePolicy)
        self.choose_image.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.choose_image.setObjectName(_fromUtf8("choose_image"))
        self.gridLayout.addWidget(self.choose_image, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.contrast_slider = QtGui.QSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contrast_slider.sizePolicy().hasHeightForWidth())
        self.contrast_slider.setSizePolicy(sizePolicy)
        self.contrast_slider.setOrientation(QtCore.Qt.Horizontal)
        self.contrast_slider.setObjectName(_fromUtf8("contrast_slider"))
        self.horizontalLayout_3.addWidget(self.contrast_slider)
        self.contrast_percent = QtGui.QLabel(self.centralwidget)
        self.contrast_percent.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.contrast_percent.setObjectName(_fromUtf8("contrast_percent"))
        self.horizontalLayout_3.addWidget(self.contrast_percent)
        self.gridLayout.addLayout(self.horizontalLayout_3, 7, 2, 1, 1)
        self.save_image_button = QtGui.QPushButton(self.centralwidget)
        self.save_image_button.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.save_image_button.setObjectName(_fromUtf8("save_image_button"))
        self.gridLayout.addWidget(self.save_image_button, 8, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Editor", None))
        self.label.setText(_translate("MainWindow", "Select Image to be edited", None))
        self.intensity_percent.setText(_translate("MainWindow", "0", None))
        self.label_3.setText(_translate("MainWindow", "Light Intensity", None))
        self.grayscale_percent.setText(_translate("MainWindow", "0", None))
        self.label_4.setText(_translate("MainWindow", "Contrast", None))
        self.choose_image.setText(_translate("MainWindow", "Select", None))
        self.label_2.setText(_translate("MainWindow", "Grayscale", None))
        self.contrast_percent.setText(_translate("MainWindow", "0", None))
        self.save_image_button.setText(_translate("MainWindow", "Save Image", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = ImageEditing()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

def createWindow():
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = ImageEditing()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
